import { NavigatorScreenParams } from "@react-navigation/native";
import { BottomTabParamList } from "./BottomTabParamList";

export type RootStackParamList = {
    DrawerNavigation: NavigatorScreenParams<BottomTabParamList>;
    Damo: undefined;
    ChooseLanguage: undefined;
    QrCodeScanner: undefined;
    SignUp: undefined;
    SignIn: undefined;
    Onbording: undefined;
    Login: undefined;
    Register: undefined;
    ForgotPassword: undefined;
    EnterCode: { contactNumber: string };
    SignUpVerifyOTP: { contactNumber: string };
    GoogleContactUpload: { userId: number; token: string };
    GoogleContactVerify: { contactNumber: string; userId: number };
    EmailVerify: undefined;
    NewPassword: undefined;
    ResetPassword: undefined;
    Settings: undefined;
    ChangePassword: undefined;
    DeleteAccount: undefined;
    HelpCenter: undefined;
    TwoStepAuthentication: undefined;
    BottomNavigation: undefined;
    SingleChat: undefined;
    Chat: undefined;
    Support: undefined;
    History: undefined;
    Verification: undefined;
    Call: undefined;
    EditProfile: undefined;
    WriteReview: { tagNo: string; itemId: string; productName?: string; productImage?: string };
    Trackorder: { orderId: string | number; seedOrder?: any };
    Products: {
        ItemName?: string;
        itemId?: string;
        metal?: string;
        title?: string;
        search?: string;
        SubItemName?: string;
        filterId?: string;
        gender?: string;
        priceRange?: string;
        occasion?: string;
        filterIds?: number | string;   // → backend List<Integer> filterIds
    } | undefined;
    Language: undefined;
    MyCart: undefined;
    Category: undefined;
    Notifications: undefined;
    Questions: undefined;
    ProductDetails: { tagKey: string };
    Writereview: undefined;
    Profile: undefined;
    Wishlist: undefined;
    Search: undefined;
    Components: undefined;
    Coupons: undefined;
    SavedAddresses: { select?: boolean } | undefined;
    Checkout: {
      /** Buy Now flow — pass the single product object, bypasses cart */
      buyNowProduct?: any;
      /** Cart selection flow — only checkout these TAGKEY values */
      selectedTagKeys?: string[];
    } | undefined;
    Addcard: undefined;
    Payment: { orderId: string | number; paymentMode: 'ONLINE' | 'COD'; paymentType?: string; totalAmount?: number };
    PaymentStatus: { orderId: string | number; mode?: string };
    SaveAddress: { id?: string | number } | undefined;
    Myorder: undefined;
    AddCard: undefined;
    Notification: undefined;
    Offers: undefined;
    OrderReturn: { orderId: string | number };
    AboutUs: undefined;
    ContactUs: undefined;
    PolicyScreen: {
      type: 'privacy' | 'terms' | 'refund' | 'shipping' | 'cancellation' | 'why-choose-us' | 'risk';
    };
    Home: undefined;
    RecentlyViewed: undefined;
    Accordion: undefined;
    ActionModals: undefined;
    BottomSheet: undefined;
    ModalBox: undefined;
    Buttons: undefined;
    Badges: undefined;
    Charts: undefined;
    Headers: undefined;
    lists: undefined;
    Pricings: undefined;
    DividerElements: undefined;
    Snackbars: undefined;
    Socials: undefined;
    Swipeable: undefined;
    Tabs: undefined;
    Tables: undefined;
    Toggles: undefined;
};